########################################################## User  #########################################################################
#Create
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "first_name": "Jhon",
    "last_name": "Doe",
    "username": "jdoe@gmail.com",
    "password": "12345678",
    "userType": "64172a3949a38f0002b88e37"
}
###

POST http://localhost:9000/api/login HTTP/1.1
Content-Type: application/json

{
    "username":"jdoe@gmail.com",
    "password":"12345678"
}
###

GET http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json


###
GET http://localhost:9000/api/users/6416657c51918c6283fd0561 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:9000/api/users/6416657c51918c6283fd0561 HTTP/1.1
Content-Type: application/json

{
    "first_name": "AlejAndrito",
    "last_name": "Montanito",
    "username": "thealejo97@gmail.com"
}
### Eliminar
DELETE http://localhost:9000/api/users/641665a751918c6283fd0564 HTTP/1.1
Content-Type: application/json

########################################################## User type ###################################################################
POST http://localhost:9000/api/userTypes HTTP/1.1
Content-Type: application/json

{
"name":"reader",
"description":"user reader, basic user reader"
}
### Listar
GET http://localhost:9000/api/userTypes HTTP/1.1
Content-Type: application/json
### Eliminar
DELETE http://localhost:9000/api/users/userTypes HTTP/1.1
Content-Type: application/json
##########################################################  Reading session ###################################################################
###Crear
POST http://localhost:9000/api/readingSession HTTP/1.1
Content-Type: application/json

{
    "book":"OL274509W",
    "total_pages":"348",
    //"start_page":"200",
    "end_page":"358",
    "time":"180",
    //"progress_user_start":"50",
    //"progress_user_end":"88",
    "comment_session":"Iniciando libro",
    "user":"64172a5e49a38f0002b88e39"
}
###listar
GET http://localhost:9000/api/readingSession HTTP/1.1
Content-Type: application/json

###get last reading sesion
GET http://localhost:9000/api/readingSession/getLastReadingSession/64172a5e49a38f0002b88e39 HTTP/1.1
Content-Type: application/json


###listar uno
GET http://localhost:9000/api/readingSession/641730ac2e6e877024008af5 HTTP/1.1
Content-Type: application/json
###Actualizar
PUT http://localhost:9000/api/readingSession/641730ac2e6e877024008af5 HTTP/1.1
Content-Type: application/json

{
    "total_pages":"348"
}
### Eliminar
DELETE http://localhost:9000/api/readingSession/64174386be082ca974f4b70e HTTP/1.1
Content-Type: application/json


##########################################################  Books ###################################################################
###search by book id key
POST http://localhost:9000/api/booksApi/getBookInfo HTTP/1.1
Content-Type: application/json

{
    "workId":"OL274574W"
}
###search by book author
POST http://localhost:9000/api/booksApi/searchBookAuthor HTTP/1.1
Content-Type: application/json

{
    "author":"Gabriel garcia"
}

###search ALL bookS
POST http://localhost:9000/api/booksApi/getAllBooks/ HTTP/1.1
Content-Type: application/json

{
    "limit":1
    
}
###search by book title
POST http://localhost:9000/api/booksApi/searchBookTitle HTTP/1.1
Content-Type: application/json

{
    "title":"El coronel no tiene"
}